logging: # logging
  level:
    org.hibernate.SQL: debug

spring:
  datasource: # db
    url: jdbc:mysql://localhost:3306/uriel?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: # jpa
    hibernate:
      ddl-auto: create-drop
      show_sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  header: Authorization
  secret: Y2hvcHBhLWRvbnQtYml0ZS1tZS1zcHJpbmctYm9vdC1qd3QtdGVzdC1zZWNyZXQta2V5LWNob3BwYS1kb250LWJpdGUtbWUtc3ByaW5nLWJvb3Qtand0LXRlc3Qtc2VjcmV0LWtleQo=
  token-validity-in-seconds: 86400

#  security: # security
#    oauth2: # oauth2
#      client:
#        registration: # OAuth ??? ? ??? Application? ??? ???? AccessToken? Authorization Server?? ???? ? ??
#          naver:
#            client-id:
#            client-secret:
#            redirect-uri:
#            authorization-grant-type: authorization_code
#            scope:
#            client-name: Naver
#
#          kakao:
#            client-id:
#            client-secret:
#            redirect-uri:
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            scope:
#            client-name:
#
#        provider: # AccessToken? Authorization Server?? ?? ?? ?, ?? AccessToken?? Resource Server? API? ??? ? provider ??? ??? ???? API ??
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response
#
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#  servlet: # file
#    multipart:
#      enabled: true
#      max-request-size:
#      max-file-size: